### ISSUE TITLE
Translate README to english?

### ISSUE THREAD

**Issue by v-zhuravlev** [drequena/zabbix-iDracDellTraps#2]
Hi! Your template appears to be in English, but its description in README is not. Can you kindly translate it to English (or provide English version as well) so Zabbix community worldwide can use it? Thank you!

**Comment by drequena** [comment]
Hi! Maybe you misses th README-en.md file. I made the translation on a separate file so it would be easier to contribute.
I'll put a link on the original README.md to the English version.

**Comment by v-zhuravlev** [comment]
Thanks!
